# -*- coding: utf-8 -*-
"""Lossless INI configuration model (plan v0.2 §5.2).

Reads every section (including listeners with Enabled False which
fakenet.parse_config would drop), preserves ordering and unknown keys, and
writes files that fakenet's default ConfigParser reads byte-compatibly:

- colon ``Key: Value`` style, ``[FakeNet]``/``[Diverter]`` exact case;
- booleans normalised per the three literal families (§3.2):
  Enabled/Hidden -> True/False, fuzzy booleans + DivertTraffic/UseSSL ->
  Yes/No;
- ``%%`` escaping round trip: file-level ``%%`` is unescaped to ``%`` in the
  model, and any ``%`` is re-escaped on write;
- every listener section is written with an Enabled key (fakenet.py:108
  crashes on a listener section without it);
- write encoding == detected source encoding, BOM preserved, new files are
  pure ASCII without BOM and CRLF (§5.2 v0.2/P2);
- save() refuses to clobber a file modified externally after load (R1).
"""

import configparser
import locale
import os
from collections import OrderedDict

from fakenet.gui import schema

FAKENET_SECTION = schema.FAKENET_SECTION
DIVERTER_SECTION = schema.DIVERTER_SECTION

NEW_FILE_HEADER = (
    '# Generated by fakenet-GUI (GUI configuration editor).\n'
    '# Syntax: [Section] headers, "Key: Value" lines. See docs for details.')

# Literal families (plan §3.2).
_TRUEFALSE_WORDS = {
    'true': 'True', 'false': 'False', '1': 'True', '0': 'False',
    'yes': 'True', 'no': 'False', 'on': 'True', 'off': 'False',
}
_YESNO_WORDS = {
    'yes': 'Yes', 'true': 'Yes', 'on': 'Yes', 'enable': 'Yes',
    'enabled': 'Yes', 'no': 'No', 'false': 'No', 'off': 'No',
    'disable': 'No', 'disabled': 'No',
}


class ExternalModifiedError(Exception):
    """The file changed on disk after it was loaded (R1 guard)."""


def unescape_percent(value):
    """File-level ``%%`` -> logical ``%`` (BasicInterpolation semantics)."""
    return value.replace('%%', '%')


def escape_percent(value):
    """Logical ``%`` -> file-level ``%%``."""
    return value.replace('%', '%%')


def expand_ports(ports_spec):
    """Mirror fakenet.fakenet.expand_ports: '80' / '80, 81' / '60000-60010'."""
    ports = []
    for token in str(ports_spec).split(','):
        token = token.strip()
        if not token:
            continue
        if '-' in token:
            low, high = token.split('-', 1)
            ports.extend(range(int(low), int(high) + 1))
        else:
            ports.append(int(token))
    return ports


class Section(object):
    """One INI section; keys keep original case, lookups are insensitive."""

    def __init__(self, name):
        self.name = name
        self._items = OrderedDict()  # original-case key -> logical value

    @property
    def is_listener(self):
        return self.name not in (FAKENET_SECTION, DIVERTER_SECTION)

    def get(self, key, default=None):
        lowered = key.lower()
        for stored, value in self._items.items():
            if stored.lower() == lowered:
                return value
        return default

    def set(self, key, value):
        value = '' if value is None else str(value)
        for stored in self._items:
            if stored.lower() == key.lower():
                self._items[stored] = value
                return
        self._items[key] = value

    def delete(self, key):
        for stored in list(self._items):
            if stored.lower() == key.lower():
                del self._items[stored]
                return

    def keys(self):
        return list(self._items.keys())

    def items(self):
        return list(self._items.items())

    def __contains__(self, key):
        return self.get(key) is not None


class ConfigModel(object):
    """Whole-file model: ordered sections + encoding/newline provenance."""

    def __init__(self):
        self.sections = OrderedDict()
        self.path = None
        self.encoding = None   # None (new) | 'utf-8-sig' | 'locale'
        self.bom = False
        self.newline = '\r\n'
        self.mtime = None
        self.kind = 'main'     # 'main' config or 'custom' response INI

    # -- section management ------------------------------------------------

    def ensure_sections(self):
        if FAKENET_SECTION not in self.sections:
            self.sections[FAKENET_SECTION] = Section(FAKENET_SECTION)
        if DIVERTER_SECTION not in self.sections:
            self.sections[DIVERTER_SECTION] = Section(DIVERTER_SECTION)
        return self

    def section(self, name):
        return self.sections.get(name)

    def ensure_section(self, name):
        if name not in self.sections:
            self.sections[name] = Section(name)
        return self.sections[name]

    def rename_section(self, old, new):
        if old not in self.sections:
            raise KeyError(old)
        if new in self.sections:
            raise ValueError('section %r already exists' % new)
        sections = OrderedDict()
        for name, sec in self.sections.items():
            sections[new if name == old else name] = sec
        self.sections = sections
        sec = self.sections[new]
        sec.name = new
        return sec

    def delete_section(self, name):
        self.sections.pop(name, None)

    def listener_sections(self):
        return [sec for sec in self.sections.values() if sec.is_listener]

    def diverter(self):
        return self.ensure_sections().sections[DIVERTER_SECTION]

    def fakenet(self):
        return self.ensure_sections().sections[FAKENET_SECTION]

    def clone(self):
        other = ConfigModel()
        other.path = self.path
        other.encoding = self.encoding
        other.bom = self.bom
        other.newline = self.newline
        other.mtime = self.mtime
        other.kind = self.kind
        for sec in self.sections.values():
            copy = Section(sec.name)
            copy._items = OrderedDict(sec._items)
            other.sections[sec.name] = copy
        return other

    # -- load / save --------------------------------------------------------

    @classmethod
    def load(cls, path):
        with open(path, 'rb') as handle:
            raw = handle.read()
        bom = raw.startswith(b'\xef\xbb\xbf')
        try:
            text = raw.decode('utf-8-sig')
            encoding = 'utf-8-sig'
        except UnicodeDecodeError:
            text = raw.decode(locale.getpreferredencoding(False))
            encoding = 'locale'
        if text.startswith('\ufeff'):
            # Defensive: a double-BOM file leaves one BOM char behind.
            text = text[1:]
        newline = '\r\n' if '\r\n' in text else '\n'
        parser = configparser.ConfigParser(interpolation=None, strict=True)
        parser.optionxform = str  # keep original key case for display
        parser.read_string(text)

        model = cls()
        model.path = os.path.abspath(path)
        model.encoding = encoding
        model.bom = bom
        model.newline = newline
        model.mtime = os.path.getmtime(path)
        for name in parser.sections():
            sec = Section(name)
            for key, value in parser.items(name, raw=True):
                sec._items[key] = unescape_percent(value)
            model.sections[name] = sec
        return model

    @classmethod
    def new_config(cls):
        model = cls()
        model.ensure_sections()
        model.fakenet().set('DivertTraffic', 'Yes')
        diverter = model.diverter()
        for field in schema.DIVERTER_FIELDS:
            if field.default and not field.lock and not field.advanced:
                diverter.set(field.key, field.default)
        proxy_tcp = model.ensure_section('ProxyTCPListener')
        proxy_tcp.set('Enabled', 'True')
        proxy_tcp.set('Protocol', 'TCP')
        proxy_tcp.set('Listener', 'ProxyListener')
        proxy_tcp.set('Port', '8080')
        proxy_tcp.set(
            'Listeners',
            'HTTPListener, RawListener, FTPListener, DNSListener, '
            'POPListener, SMTPListener, TFTPListener, IRCListener')
        proxy_tcp.set('Hidden', 'False')
        proxy_tcp.set('Static_CA', 'No')
        proxy_tcp.set('CA_Cert', 'configs/fakenet_ca.crt')
        proxy_tcp.set('CA_Key', 'configs/fakenet_ca.key')

        proxy_udp = model.ensure_section('ProxyUDPListener')
        proxy_udp.set('Enabled', 'True')
        proxy_udp.set('Protocol', 'UDP')
        proxy_udp.set('Listener', 'ProxyListener')
        proxy_udp.set('Port', '38926')
        proxy_udp.set(
            'Listeners',
            'RawListener, DNSListener, TFTPListener, FTPListener')
        proxy_udp.set('Hidden', 'False')

        # Content listeners (plan 2026.08.21-01 I6): without a real
        # HTTPListener on 80/443 the proxy cannot dispatch HTTP and browser
        # custom replies stay unreachable. Keys mirror upstream
        # configs/default.ini [HTTPListener80]/[HTTPListener443].
        for name, port, use_ssl in (('HTTPListener80', '80', 'No'),
                                     ('HTTPListener443', '443', 'Yes')):
            section = model.ensure_section(name)
            section.set('Enabled', 'True')
            section.set('Port', port)
            section.set('Protocol', 'TCP')
            section.set('Listener', 'HTTPListener')
            section.set('UseSSL', use_ssl)
            section.set('Webroot', 'defaultFiles/')
            section.set('Timeout', '10')
            section.set('DumpHTTPPosts', 'Yes')
            section.set('DumpHTTPPostsFilePrefix', 'http')
            section.set('Hidden', 'False')
        return model

    def render(self, header=None):
        lines = [header if header is not None else NEW_FILE_HEADER]
        for sec in self.sections.values():
            lines.append('')
            lines.append('[%s]' % sec.name)
            # Only main-config listener sections require Enabled
            # (fakenet.py:108); custom-response [Example*] sections must
            # not be polluted with it.
            if (self.kind == 'main' and sec.is_listener and
                    'Enabled' not in sec):
                lines.append('Enabled: True')
            for key, value in sec.items():
                key = self._display_key(sec, key)
                value = self._canonical_literal(sec, key, value)
                parts = escape_percent(value).split('\n')
                lines.append('%s: %s' % (key, parts[0]))
                for continuation in parts[1:]:
                    lines.append('    %s' % continuation)
        return self.newline.join(lines) + self.newline

    def _display_key(self, sec, key):
        lowered = key.lower()
        if sec.name == FAKENET_SECTION:
            field = schema.fakenet_field(lowered)
        elif sec.name == DIVERTER_SECTION:
            field = schema.diverter_field(lowered)
        else:
            field = (schema._LISTENER_COMMON_BY_KEY.get(lowered) or
                     schema._LISTENER_TYPE_BY_KEY.get(
                         sec.get('Listener', ''), {}).get(lowered))
        return field.key if field else key

    def _canonical_literal(self, sec, key, value):
        lowered = key.lower()
        wtype = None
        if sec.name == DIVERTER_SECTION:
            field = schema.diverter_field(lowered)
            wtype = field.wtype if field else None
        elif sec.name == FAKENET_SECTION:
            field = schema.fakenet_field(lowered)
            wtype = field.wtype if field else None
        else:
            field = (schema._LISTENER_COMMON_BY_KEY.get(lowered) or
                     schema._LISTENER_TYPE_BY_KEY.get(
                         sec.get('Listener', ''), {}).get(lowered))
            wtype = field.wtype if field else None
        if wtype == schema.T_BOOL_TRUEFALSE:
            return _TRUEFALSE_WORDS.get(value.strip().lower(), value)
        if wtype == schema.T_BOOL_YESNO:
            return _YESNO_WORDS.get(value.strip().lower(), value)
        return value

    def save(self, path=None):
        path = os.path.abspath(path or self.path)
        if not path:
            raise ValueError('no path')
        if self.mtime is not None and os.path.exists(path):
            if os.path.getmtime(path) != self.mtime:
                raise ExternalModifiedError(
                    'file modified after load: %s' % path)
        text = self.render()
        if self.encoding == 'utf-8-sig':
            data = text.encode('utf-8-sig' if self.bom else 'utf-8')
        elif self.encoding == 'locale':
            data = text.encode(locale.getpreferredencoding(False))
        else:
            try:
                data = text.encode('ascii')
            except UnicodeEncodeError:
                data = text.encode('utf-8')
        with open(path, 'wb') as handle:
            handle.write(data)
        self.path = path
        self.mtime = os.path.getmtime(path)
        return path

    # -- listener expansion preview ----------------------------------------

    def expanded_listener_names(self, sec):
        """Names fakenet.expand_listeners would produce for this section."""
        spec = sec.get('Port')
        if spec is None or str(spec).strip() == '':
            return []
        ports = expand_ports(spec)
        if len(ports) > 1:
            return ['%s_%d' % (sec.name, port) for port in ports]
        return [sec.name]
